expense_tracker_app/expense_tracker_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expenses.urls')),
]

expense_tracker_app/expenses/urls.py
from django.urls import path
from . import views
from .views import Home, Add_Expense, Delete_Expense, Edit_Expense

app_name = 'expenses'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('add/', Add_Expense.as_view(), name='add_expense'),
    path('edit_expense/<int:id>/', Edit_Expense.as_view(), name='edit_expense'),
    path('delete_expense/<int:id>/', Delete_Expense.as_view(), name='delete_expense'),
]

expense_tracker_app/expenses/models.py
from django.db import models

# Create your models here.


class Expense(models.Model):
    title = models.TextField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()

    def __str__(self):
        return self.title

expense_tracker_app/expenses/forms.py
from django import forms
from .models import Expense

class AddExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['title', 'amount', 'date']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'date': forms.DateInput(attrs={'class': 'form-control'}),
        }

expense_tracker_app/expenses/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Expense
from .forms import AddExpenseForm
from django.views import View
# Create your views here.


class Home(View):
    def get(self, request):
        expense_data = Expense.objects.all()
        return render(request, 'expenses/landing.html', {'expense_data': expense_data})


class Add_Expense(View):
    def get(self, request):
        form = AddExpenseForm
        return render(request, 'expenses/add_expense.html', {'form': form})

    def post(self, request):
        form = AddExpenseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return render(request, 'expenses/add_expense.html', {'form': form})


class Delete_Expense(View):
    def post(self, request, id):  # Include 'id' as an argument
        expense_data = Expense.objects.get(id=id)
        expense_data.delete()
        return redirect('/')


class Edit_Expense(View):
    def get(self, request, id):
        expense_data = get_object_or_404(Expense, id=id)
        form = AddExpenseForm(instance=expense_data)
        return render(request, 'expenses/edit_expense.html', {'form': form})

    def post(self, request, id):
        expense_data = get_object_or_404(Expense, id=id)
        form = AddExpenseForm(request.POST, instance=expense_data)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return render(request, 'expenses/edit_expense.html', {'form': form})

expense_tracker_app/expenses/templates/expenses/add_expense.html
{% extends "base.html" %}

{% block content %}
<h1 class='text-center  mt-5'>Add Expense</h1>
<div class='row justify-content-around mt-5'>
    <div class='col-sm-8'>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class='btn btn-primary'>Save Expense</button>
</form>
</div>
</div>
{% endblock content %}

expense_tracker_app/expenses/templates/expenses/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} | Expense Tracker App</title>
    <link rel='stylesheet' href="{% static 'css/base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<style>
    body {
        background-color: rgb(96, 5, 119);
        color: #fff;
        overflow : hidden;
    }
</style>
<body>
        {% block content %}
        {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

expense_tracker_app/expenses/templates/expenses/edit_expense.html
{% extends "base.html" %}

{% block content %}
<h1 class='text-center  mt-5'>Edit Expense</h1>
<div class='row justify-content-around mt-5'>
    <div class='col-sm-8'>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class='btn btn-primary'>Edit Expense</button>
</form>
</div>
</div>
{% endblock content %}

expense_tracker_app/expenses/templates/expenses/landing.html
 {% extends "base.html" %}

 {% block title %}Landing Page{% endblock title %}
 {% block content %}
<section class='container'>
    <div class='row justify-content-around text-center mt-5'>
        <div class='col-sm-8'>
            <h1>Expense Tracker App </h1>
        </div>
    </div>
</section>
<section class='container'>
    <div class='row'>
        <div class='col-sm-8'>
            <a href='/add' class='btn btn-primary'>ADD EXPENSE</a>
        </div>
    </div>
    <div class='row justify-content-around text-center mt-5'>
        <div class='col-sm-8'>
            <table class="table">
                <thead>
                    <tr>
                      <th scope="col">S.No.</th>
                      <th scope="col">Title</th>
                      <th scope="col">Amount</th>
                      <th scope="col">Date</th>
                      <th scope="col" colspan="2">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for expense in expense_data %}
                    <tr>
                      <th scope="row">{{forloop.counter}}</th>
                      <td>{{expense.title}}</td>
                      <td>{{expense.amount}}</td>
                      <td>{{expense.date}}</td>
                      <td>
                        <form action="{% url 'expenses:delete_expense' id=expense.id %}" method="POST">

                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{ expense.id }}">
                            <input type="submit" value="Delete" class="btn btn-danger">
                        </form>
                      </td>
                      <td>
                        <a href="{% url 'expenses:edit_expense' id=expense.id %}" class="btn btn-info">Edit</a>

                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
              </table>
        </div>
    </div>
</section>
 {% endblock content %}